PRINT_FREQ: 10
DIST_BACKEND: "nccl"
INIT_METHOD: "env://"
OUTPUT_DIR: 'outputs/efficientnet_lite4_cccf_300_b128_e90_g4_mixup'
TRAIN:
  EVAL_EPOCH: 1
  START_EPOCH: 1
  MAX_EPOCH: 90
DATALOADER:
  TRAIN_BATCH_SIZE: 128
  TEST_BATCH_SIZE: 128
  NUM_WORKERS: 4
  RANDOM_SAMPLE: True
  COLLATE_FN: 'default'
DATASET:
  NAME: 'CCCF'
  TRAIN_ROOT: './data/cccf'
  TEST_ROOT: './data/cccf'
TRANSFORM:
  TRAIN_METHODS: ('RandomResizedCrop', 'RandomHorizontalFlip', 'RandAugment', 'ToTensor', 'RandomErasing')
  TEST_METHODS: ('Resize', 'CenterCrop', 'ToTensor')
  TRAIN_RESIZE_CROP: (300,)
  RandomErasing: (0.5, (0.02, 0.33), (0.3, 3.3), 0, False)
  TEST_RESIZE: (320,)
  TEST_CROP: (300,)
  NORMALIZE: ((0.45, 0.45, 0.45), (0.225, 0.225, 0.225), False, 1.0)
  MIXUP:
    MIXUP_ENABLED: True
    MIXUP_ALPHA: 0.8
    CUTMIX_ALPHA: 1.0
    CUTMIX_MINMAX: None
    MIXUP_PROB: 0.1
    MIXUP_SWITCH_PROB: 0.5
    MIXUP_MODE: 'batch'
MODEL:
  ARCH: 'efficientnet_lite4'
  PRETRAINED: False
  NUM_CLASSES: 502
  SYNC_BN: False
  CRITERION:
    NAME: 'cross_entropy_loss'
    REDUCTION: 'mean'
OPTIMIZER:
  NAME: 'sgd'
  LR: 1e-1
  MOMENTUM: 0.9
  WEIGHT_DECAY:
    DECAY: 4e-5
    NO_BIAS: False
    NO_NORM: False
LR_SCHEDULER:
  NAME: 'multi_step_lr'
  IS_WARMUP: True
  WARMUP_EPOCH: 5
  MULTISTEP_LR:
    MILESTONES: [ 25, 55, 75 ]
    GAMMA: 0.1