PRINT_FREQ: 10
DIST_BACKEND: "nccl"
INIT_METHOD: "env://"
OUTPUT_DIR: 'outputs/r50_cccf_224_b256_e90_g4'
TRAIN:
  EVAL_EPOCH: 1
  START_EPOCH: 1
  MAX_EPOCH: 90
DATALOADER:
  TRAIN_BATCH_SIZE: 256
  TEST_BATCH_SIZE: 256
  NUM_WORKERS: 4
  RANDOM_SAMPLE: True
DATASET:
  NAME: 'CCCF'
  TRAIN_ROOT: './data/cccf'
  TEST_ROOT: './data/cccf'
TRANSFORM:
  TRAIN_METHODS: ('RandomResizedCrop', 'RandomHorizontalFlip')
  TEST_METHODS: ('Resize', 'CenterCrop')
  TRAIN_RESIZE_CROP: (224,)
  TEST_RESIZE: (256,)
  TEST_CROP: (224,)
  NORMALIZE: ((0.485, 0.456, 0.406), (0.229, 0.224, 0.225), False)
MODEL:
  ARCH: 'resnet50'
  PRETRAINED: True
  NUM_CLASSES: 502
  SYNC_BN: False
  CRITERION:
    NAME: 'CrossEntropyLoss'
    REDUCTION: 'mean'
OPTIMIZER:
  NAME: 'SGD'
  LR: 1e-1
  MOMENTUM: 0.9
  WEIGHT_DECAY:
    DECAY: 1e-4
    NO_BIAS: True
    NO_NORM: True
LR_SCHEDULER:
  NAME: 'MultiStepLR'
  IS_WARMUP: True
  WARMUP_EPOCH: 5
  MULTISTEP_LR:
    MILESTONES: [ 25, 55, 75 ]
    GAMMA: 0.1