RNG_SEED: 1
DIST_BACKEND: "nccl"
INIT_METHOD: "env://"
OUTPUT_DIR: 'outputs/cifar_imagenet_224_b256_e90'
#TRAIN:
#  LOG_STEP: 10
#  SAVE_EPOCH: 5
#  EVAL_EPOCH: 5
#  MAX_EPOCH: 200
#  RESUME: False
DATALOADER:
  TRAIN_BATCH_SIZE: 256
  TEST_BATCH_SIZE: 256
  NUM_WORKERS: 4
  RANDOM_SAMPLE: True
DATASET:
  NAME: 'GeneralDatasetV2'
  TRAIN_ROOT: '/home/mk/repos/data/cifar/zcls_cifar/train'
  TEST_ROOT: '/home/mk/repos/data/cifar/zcls_cifar/test'
#TRANSFORM:
#  NORMALIZE: ((0.485, 0.456, 0.406), (0.229, 0.224, 0.225), 255.0, 1.0)
MODEL:
  ARCH: 'resnet18'
  PRETRAINED: True
  NUM_CLASSES: 100
  SYNC_BN: False
  CRITERION:
    NAME: 'CrossEntropyLoss'
    REDUCTION: 'mean'