PRINT_FREQ: 10
DIST_BACKEND: "nccl"
INIT_METHOD: "env://"
OUTPUT_DIR: 'outputs/cifar_imagenet_224_b256_e90'
TRAIN:
  EVAL_EPOCH: 1
  START_EPOCH: 0
  MAX_EPOCH: 90
DATALOADER:
  TRAIN_BATCH_SIZE: 256
  TEST_BATCH_SIZE: 256
  NUM_WORKERS: 4
  RANDOM_SAMPLE: True
DATASET:
  NAME: 'GeneralDatasetV2'
  TRAIN_ROOT: '/home/zj/repos/ZCls2/data/cifar/zcls_cifar/train'
  TEST_ROOT: '/home/zj/repos/ZCls2/data/cifar/zcls_cifar/test'
TRANSFORM:
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
MODEL:
  ARCH: 'resnet18'
  PRETRAINED: True
  NUM_CLASSES: 100
  SYNC_BN: False
  CRITERION:
    NAME: 'CrossEntropyLoss'
    REDUCTION: 'mean'
OPTIMIZER:
  NAME: 'SGD'
  LR: 1e-1
  MOMENTUM: 0.9
  WEIGHT_DECAY:
    DECAY: 1e-4
    NO_BIAS: True
    NO_NORM: True
LR_SCHEDULER:
  NAME: 'MultiStepLR'
  IS_WARMUP: True
  WARMUP_EPOCH: 5
  MULTISTEP_LR:
    MILESTONES: [ 30, 60, 80 ]
    GAMMA: 0.1